### ISSUE TITLE
Quality requirements for `ros2_control` packages

### ISSUE THREAD

**Issue by destogl** [ros-controls/roadmap#20]
Hi,

working on `ros2_control_demos` package I found a few interesting stuff regarding the quality or ROS2 packages. I would like to document those here and we could use it to discuss what we would like to have in the short and long run. So I propose an initial list and hope for some feedback :)

List of quality requirement for `ros2_control*`-packages:

- [ ] GitHub Actions for CI, Lint and CodeCoverage (e.g. see [ros2_control_demos](https://github.com/ros-controls/ros2_control_demos/actions) package)
- [ ] Templates for Issues and PRs - [GitHub-Doku](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates) - [Example-rclcpp](https://github.com/ros2/rclcpp/blob/master/.github/ISSUE_TEMPLATE.md)
- [ ] Quality Declaration - [REP2004](https://www.ros.org/reps/rep-2004.html#quality-level-1) [Example-rclcpp](https://github.com/ros2/rclcpp/blob/master/rclcpp/QUALITY_DECLARATION.md)
- [ ] ros-controls/ros2_control#21
- [ ] ros-controls/ros2_control#22
- [ ] ros-controls/ros2_control#23

**Comment by bmagyar** [comment]
I've added this to the agenda for the next meeting

**Comment by fkromer** [comment]
Are you guys planning to consider [IEC 62443](https://de.wikipedia.org/wiki/IEC_62443) (Insutrial communication networks - IT security for networks and systems) and [IEC 61131](https://en.wikipedia.org/wiki/IEC_61131) (IEC61508 applied to PLCs) as well? It would be very optmistic to comply with them in the first place. But at least considering them could result in a high level design which would people help to migrate ros2_control to a certifiable solution. Equivalent to how Apex.AI did with their ROS2 fork for the automotive domain.

**Comment by destogl** [comment]
HI @fkromer, thanks for the references. We are currently very working mostly on the basic structure to provide easier use than ros_control in ROS1. Nevertheless, this is a very good point. We will add this to our agenda for the next meeting and discuss it. Do you have any experince with this norms? Maybe you could joint the meeting and explain/present your ideas?
